// AUTO-GENERATED by scripts/sync-lots-from-master-sheet.mjs
// DO NOT EDIT BY HAND — your changes will be overwritten on next build.
// To update lot data: edit the master Google Sheet
// (1ES3JjgZaqj_uEci3DdExDF-eC8eumDz0wrvb8avEB9g) and re-run sync.
//
// Synced: 2026-05-26T22:24:42.245Z
// Source: Apps Script ?api=lot-inventory

import type { Lot } from './lots';

export const generatedMasterLots: Lot[] = [
  {
    "id": "hawks-landing-L8B7D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 8, Block 7",
    "address": "3406 Chester Dr / 6439 Hillsdale Ln",
    "acres": 0.559,
    "price": 148000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L11B7D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 11, Block 7",
    "address": "3290 Chester Dr",
    "acres": 0.511,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L3B8D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 3, Block 8",
    "address": "6436 Hillsdale Ln",
    "acres": 0.427,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L3B9D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 3, Block 9",
    "address": "3299 Chester Dr",
    "acres": 0.543,
    "price": 139000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L5B9D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 5, Block 9",
    "address": "3363 Chester Dr",
    "acres": 0.523,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L6B9D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 6, Block 9",
    "address": "3397 Chester Dr / 6485 Hillsdale Ln",
    "acres": 0.572,
    "price": 139000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L9B9D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 9, Block 9",
    "address": "3340 Granger St",
    "acres": 0.609,
    "price": 169000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L10B9D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 10, Block 9",
    "address": "3304 Granger St",
    "acres": 0.613,
    "price": 169000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L1B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 1, Block 10",
    "address": "3097 Granger St / 6624 Crown Crescent",
    "acres": 0.68,
    "price": 139000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L2B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 2, Block 10",
    "address": "3066 Lancer Ave / 6640 Crown Crescent",
    "acres": 0.819,
    "price": 144000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L8B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 8, Block 10",
    "address": "3303 Granger St",
    "acres": 0.533,
    "price": 139000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L9B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 9, Block 10",
    "address": "3333 Granger St",
    "acres": 0.541,
    "price": 139000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L10B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 10, Block 10",
    "address": "3363 Granger St",
    "acres": 0.55,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L11B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 11, Block 10",
    "address": "3395 Granger St",
    "acres": 0.538,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L12B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 12, Block 10",
    "address": "3429 Granger St",
    "acres": 0.503,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L13B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 13, Block 10",
    "address": "3461 Granger St",
    "acres": 0.528,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L14B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 14, Block 10",
    "address": "3493 Granger St",
    "acres": 0.55,
    "price": 134000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L20B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 20, Block 10",
    "address": "3384 Lancer Ave",
    "acres": 0.55,
    "price": 174000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L21B10D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 21, Block 10",
    "address": "3344 Lancer Ave",
    "acres": 0.505,
    "price": 174000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L6B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 6, Block 11",
    "address": "3185 Lancer Ave",
    "acres": 0.684,
    "price": 149000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L7B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 7, Block 11",
    "address": "3235 Lancer Ave",
    "acres": 0.717,
    "price": 149000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L8B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 8, Block 11",
    "address": "3287 Lancer Ave",
    "acres": 0.75,
    "price": 159000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L9B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 9, Block 11",
    "address": "3337 Lancer Ave",
    "acres": 0.807,
    "price": 159000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L10B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 10, Block 11",
    "address": "3377 Lancer Ave",
    "acres": 0.808,
    "price": 159000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L11B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 11, Block 11",
    "address": "3407 Lancer Ave",
    "acres": 0.916,
    "price": 159000,
    "status": "available"
  },
  {
    "id": "hawks-landing-L12B11D4",
    "communitySlug": "hawks-landing",
    "lotNumber": "Lot 12, Block 11",
    "address": "3439 Lancer Ave",
    "acres": 0.969,
    "price": 159000,
    "status": "available"
  },
  {
    "id": "granite-creek-L8B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 8, Block 4",
    "address": "5204 Eagle Creek Rd",
    "acres": 0.367,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2901 Granite Falls Dr"
  },
  {
    "id": "granite-creek-L9B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 9, Block 4",
    "address": "5170 Eagle Creek Rd",
    "acres": 0.335,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L10B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 10, Block 4",
    "address": "5136 Eagle Creek Rd",
    "acres": 0.339,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L11B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 11, Block 4",
    "address": "5102 Eagle Creek Rd",
    "acres": 0.341,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L12B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 12, Block 4",
    "address": "5068 Eagle Creek Rd",
    "acres": 0.343,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L13B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 13, Block 4",
    "address": "5034 Eagle Creek Rd",
    "acres": 0.345,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L14B4D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 14, Block 4",
    "address": "4998 Eagle Creek Rd",
    "acres": 0.42,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2894 Spring Gulch Dr"
  },
  {
    "id": "granite-creek-L2B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 2, Block 5",
    "address": "2887 Spring Gulch Dr",
    "acres": 0.3,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L3B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 3, Block 5",
    "address": "2905 Spring Gulch Dr",
    "acres": 0.301,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L4B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 4, Block 5",
    "address": "2921 Spring Gulch Dr",
    "acres": 0.605,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L5B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 5, Block 5",
    "address": "2947 Spring Gulch Dr",
    "acres": 0.628,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L6B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 6, Block 5",
    "address": "4989 Eagle Creek Rd",
    "acres": 0.561,
    "price": 145000,
    "status": "available",
    "notes": "Corner with Spring Gulch Dr"
  },
  {
    "id": "granite-creek-L7B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 7, Block 5",
    "address": "5025 Eagle Creek Rd",
    "acres": 0.288,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L8B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 8, Block 5",
    "address": "5055 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L9B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 9, Block 5",
    "address": "5085 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L10B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 10, Block 5",
    "address": "5115 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L11B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 11, Block 5",
    "address": "5145 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L12B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 12, Block 5",
    "address": "5175 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L13B5D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 13, Block 5",
    "address": "5205 Eagle Creek Rd",
    "acres": 0.328,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2989 Granite Falls Dr"
  },
  {
    "id": "granite-creek-L3B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 3, Block 7",
    "address": "2890 Granite Falls Dr",
    "acres": 0.268,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L4B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 4, Block 7",
    "address": "2908 Granite Falls Dr",
    "acres": 0.266,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L5B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 5, Block 7",
    "address": "2924 Granite Falls Dr",
    "acres": 0.266,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L6B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 6, Block 7",
    "address": "2942 Granite Falls Dr",
    "acres": 0.266,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L7B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 7, Block 7",
    "address": "2958 Granite Falls Dr",
    "acres": 0.266,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L8B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 8, Block 7",
    "address": "2974 Granite Falls Dr",
    "acres": 0.266,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L9B7D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 9, Block 7",
    "address": "2992 Granite Falls Dr",
    "acres": 0.267,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L1B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 1, Block 12",
    "address": "5011 Eagle Creek Rd",
    "acres": 0.488,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L2B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 2, Block 12",
    "address": "5047 Eagle Creek Rd",
    "acres": 0.303,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L3B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 3, Block 12",
    "address": "5077 Eagle Creek Rd",
    "acres": 0.303,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L4B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 4, Block 12",
    "address": "5111 Eagle Creek Rd",
    "acres": 0.303,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L5B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 5, Block 12",
    "address": "5141 Eagle Creek Rd",
    "acres": 0.303,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L6B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 6, Block 12",
    "address": "5173 Eagle Creek Rd",
    "acres": 0.303,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L7B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 7, Block 12",
    "address": "5207 Eagle Creek Rd",
    "acres": 0.327,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2929 Granite Falls Dr"
  },
  {
    "id": "granite-creek-L8B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 8, Block 12",
    "address": "5208 Eagle Creek Rd",
    "acres": 0.327,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2953 Granite Falls Dr"
  },
  {
    "id": "granite-creek-L9B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 9, Block 12",
    "address": "5178 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L10B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 10, Block 12",
    "address": "5148 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L11B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 11, Block 12",
    "address": "5118 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L12B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 12, Block 12",
    "address": "5088 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L13B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 13, Block 12",
    "address": "5058 Eagle Creek Rd",
    "acres": 0.289,
    "price": 145000,
    "status": "available"
  },
  {
    "id": "granite-creek-L14B12D3",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 14, Block 12",
    "address": "5028 Eagle Creek Rd",
    "acres": 0.371,
    "price": 145000,
    "status": "available",
    "notes": "Corner — alt address 2954 Spring Gulch Dr"
  },
  {
    "id": "granite-creek-L30B2D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 30, Block 2",
    "acres": 0.457,
    "price": 125000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L19B3D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 19, Block 3",
    "acres": 0.376,
    "price": 121000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L2B6D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 2, Block 6",
    "acres": 0.335,
    "price": 121000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L6B6D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 6, Block 6",
    "acres": 0.344,
    "price": 121000,
    "status": "sold"
  },
  {
    "id": "granite-creek-L7B6D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 7, Block 6",
    "acres": 0.338,
    "price": 121000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L8B6D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 8, Block 6",
    "acres": 0.34,
    "price": 121000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L17B6D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 17, Block 6",
    "acres": 0.332,
    "price": 121000,
    "status": "sold"
  },
  {
    "id": "granite-creek-L2B9D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 2, Block 9",
    "acres": 0.454,
    "price": 125000,
    "status": "spec-in-progress"
  },
  {
    "id": "granite-creek-L1B11D2",
    "communitySlug": "granite-creek",
    "lotNumber": "Lot 1, Block 11",
    "acres": 0.392,
    "price": 121000,
    "status": "sold"
  },
  {
    "id": "sand-creek-estates-L1B5D2",
    "communitySlug": "sand-creek-estates",
    "lotNumber": "Lot 1, Block 5",
    "address": "1742 Tidepool / 5441 Boardwalk",
    "acres": 0.298,
    "price": 107000,
    "status": "available"
  },
  {
    "id": "sand-creek-estates-L2B5D2",
    "communitySlug": "sand-creek-estates",
    "lotNumber": "Lot 2, Block 5",
    "address": "5471 Boardwalk Rd",
    "acres": 0.264,
    "price": 107000,
    "status": "available"
  },
  {
    "id": "sand-creek-estates-L3B5D2",
    "communitySlug": "sand-creek-estates",
    "lotNumber": "Lot 3, Block 5",
    "address": "5505 Boardwalk Rd",
    "acres": 0.265,
    "price": 107000,
    "status": "available"
  },
  {
    "id": "sand-creek-estates-L9B4D2",
    "communitySlug": "sand-creek-estates",
    "lotNumber": "Lot 9, Block 4",
    "address": "1661 Sandbar St",
    "acres": 0.255,
    "price": 107000,
    "status": "available"
  },
  {
    "id": "sand-creek-estates-L10B4D2",
    "communitySlug": "sand-creek-estates",
    "lotNumber": "Lot 10, Block 4",
    "address": "1639 Sandbar",
    "acres": 0.253,
    "price": 107000,
    "status": "spec-in-progress"
  },
  {
    "id": "the-parks-L25B6D2",
    "communitySlug": "the-parks",
    "lotNumber": "Lot 25, Block 6",
    "acres": 0.51,
    "price": 115000,
    "status": "spec-in-progress"
  },
  {
    "id": "the-parks-L12B9D2",
    "communitySlug": "the-parks",
    "lotNumber": "Lot 12, Block 9",
    "acres": 0.75,
    "price": 125000,
    "status": "spec-in-progress"
  },
  {
    "id": "moser-estates-L4B2D1",
    "communitySlug": "moser-estates",
    "lotNumber": "Lot 4, Block 2",
    "acres": 1.01,
    "price": 110000,
    "status": "spec-in-progress"
  }
];
