// Lot inventory — source of truth for the /available-lots/ page.
//
// Two flavors of lots, both displayed in the lots table:
//   1. MANUAL LOTS — Curtis-curated raw lots from developer pricing sheets
//      (e.g., Hawks Landing Div 4 pricing PDF, Granite Creek Block 4/5/7/12).
//      Edit the `manualLots` array below directly.
//   2. PIPELINE LOTS — auto-generated by scripts/sync-odyssey-jobs.mjs from
//      the Job Progress sheet (specs with dig date > 90 days out, where the
//      plan is still flexible). Don't edit `generatedPipelineLots` by hand —
//      edit the sheet and re-run the sync. See `.claude/skills/sync-odyssey-jobs/SKILL.md`.
//
// Status legend:
//   'available'      — open for sale, primary CTA
//   'reserved'       — buyer in early conversation, not yet under contract
//   'under-contract' — purchase agreement signed, not yet closed
//   'sold'           — closed; keep visible briefly for activity signal,
//                       then remove after ~30 days
//
// Pricing: leave `price` undefined to show "Coming Soon" instead of $.

import { generatedMasterLots } from './_generatedMasterLots';

export type LotStatus = 'available' | 'spec-in-progress' | 'reserved' | 'under-contract' | 'sold';

export interface Lot {
  id: string;                  // Stable unique id, e.g. 'hawks-landing-l13b10'
  communitySlug: string;       // Matches Community.slug in communities.ts
  lotNumber: string;           // Display label ("Lot 13, Block 10")
  parcelNumber?: string;       // County parcel id (RPB...) — internal reference
  address?: string;            // Street address
  acres?: number;              // Lot size in acres
  sqFt?: number;               // Alt lot size in sq ft (sub-acre lots)
  price?: number;              // USD asking price for the raw lot
  status: LotStatus;
  compatiblePlans?: string[];  // Slugs from plans.ts — plans that fit (or empty = all)
  notes?: string;              // Buyer-facing note
}

// Hawks Landing Division 4 — source: Hawks Landing Div 4 Pricing PDF (MAY 2026)
// Curtis 2026-05-26: "These are what's available in Hawks. Everything else is now sold or gone."
//
// Granite Creek Division 3 — source: Curtis 2026-05-26. These are the lots
// Odyssey has locked/owns and is offering for build-to-suit. Pricing and
// addresses TBD (Curtis to provide separately).
const manualLots: Lot[] = [
  // ── GRANITE CREEK DIVISION 3 (Odyssey-locked lots, build-to-suit) ───────
  // Block 4 — lots 8-14
  { id: 'granite-creek-l8b4',  communitySlug: 'granite-creek', lotNumber: 'Lot 8, Block 4',  status: 'available' },
  { id: 'granite-creek-l9b4',  communitySlug: 'granite-creek', lotNumber: 'Lot 9, Block 4',  status: 'available' },
  { id: 'granite-creek-l10b4', communitySlug: 'granite-creek', lotNumber: 'Lot 10, Block 4', status: 'available' },
  { id: 'granite-creek-l11b4', communitySlug: 'granite-creek', lotNumber: 'Lot 11, Block 4', status: 'available' },
  { id: 'granite-creek-l12b4', communitySlug: 'granite-creek', lotNumber: 'Lot 12, Block 4', status: 'available' },
  { id: 'granite-creek-l13b4', communitySlug: 'granite-creek', lotNumber: 'Lot 13, Block 4', status: 'available' },
  { id: 'granite-creek-l14b4', communitySlug: 'granite-creek', lotNumber: 'Lot 14, Block 4', status: 'available' },
  // Block 5 — lots 4-13
  { id: 'granite-creek-l4b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 4, Block 5',  status: 'available' },
  { id: 'granite-creek-l5b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 5, Block 5',  status: 'available' },
  { id: 'granite-creek-l6b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 6, Block 5',  status: 'available' },
  { id: 'granite-creek-l7b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 7, Block 5',  status: 'available' },
  { id: 'granite-creek-l8b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 8, Block 5',  status: 'available' },
  { id: 'granite-creek-l9b5',  communitySlug: 'granite-creek', lotNumber: 'Lot 9, Block 5',  status: 'available' },
  { id: 'granite-creek-l10b5', communitySlug: 'granite-creek', lotNumber: 'Lot 10, Block 5', status: 'available' },
  { id: 'granite-creek-l11b5', communitySlug: 'granite-creek', lotNumber: 'Lot 11, Block 5', status: 'available' },
  { id: 'granite-creek-l12b5', communitySlug: 'granite-creek', lotNumber: 'Lot 12, Block 5', status: 'available' },
  { id: 'granite-creek-l13b5', communitySlug: 'granite-creek', lotNumber: 'Lot 13, Block 5', status: 'available' },
  // Block 7 — lots 5-7
  { id: 'granite-creek-l5b7',  communitySlug: 'granite-creek', lotNumber: 'Lot 5, Block 7',  status: 'available' },
  { id: 'granite-creek-l6b7',  communitySlug: 'granite-creek', lotNumber: 'Lot 6, Block 7',  status: 'available' },
  { id: 'granite-creek-l7b7',  communitySlug: 'granite-creek', lotNumber: 'Lot 7, Block 7',  status: 'available' },
  // Block 12 — lots 1-10
  { id: 'granite-creek-l1b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 1, Block 12',  status: 'available' },
  { id: 'granite-creek-l2b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 2, Block 12',  status: 'available' },
  { id: 'granite-creek-l3b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 3, Block 12',  status: 'available' },
  { id: 'granite-creek-l4b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 4, Block 12',  status: 'available' },
  { id: 'granite-creek-l5b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 5, Block 12',  status: 'available' },
  { id: 'granite-creek-l6b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 6, Block 12',  status: 'available' },
  { id: 'granite-creek-l7b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 7, Block 12',  status: 'available' },
  { id: 'granite-creek-l8b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 8, Block 12',  status: 'available' },
  { id: 'granite-creek-l9b12',  communitySlug: 'granite-creek', lotNumber: 'Lot 9, Block 12',  status: 'available' },
  { id: 'granite-creek-l10b12', communitySlug: 'granite-creek', lotNumber: 'Lot 10, Block 12', status: 'available' },

  // ── HAWKS LANDING DIVISION 4 ───────────────────────────────────────────
  // Block 7
  { id: 'hawks-landing-l8b7',  communitySlug: 'hawks-landing', lotNumber: 'Lot 8, Block 7',  parcelNumber: 'RPB3225007008O', address: '3406 Chester Dr / 6439 Hillsdale Ln', acres: 0.559, price: 148000, status: 'available' },
  { id: 'hawks-landing-l11b7', communitySlug: 'hawks-landing', lotNumber: 'Lot 11, Block 7', parcelNumber: 'RPB3225007011O', address: '3290 Chester Dr',                       acres: 0.511, price: 145000, status: 'available' },

  // Block 8
  { id: 'hawks-landing-l3b8',  communitySlug: 'hawks-landing', lotNumber: 'Lot 3, Block 8',  parcelNumber: 'RPB3225008003O', address: '6436 Hillsdale Ln',                     acres: 0.427, price: 134000, status: 'available' },

  // Block 9
  { id: 'hawks-landing-l3b9',  communitySlug: 'hawks-landing', lotNumber: 'Lot 3, Block 9',  parcelNumber: 'RPB3225009003O', address: '3299 Chester Dr',                       acres: 0.543, price: 139000, status: 'available' },
  { id: 'hawks-landing-l5b9',  communitySlug: 'hawks-landing', lotNumber: 'Lot 5, Block 9',  parcelNumber: 'RPB3225009005O', address: '3363 Chester Dr',                       acres: 0.523, price: 134000, status: 'available' },
  { id: 'hawks-landing-l6b9',  communitySlug: 'hawks-landing', lotNumber: 'Lot 6, Block 9',  parcelNumber: 'RPB3225009006O', address: '3397 Chester Dr / 6485 Hillsdale Ln',  acres: 0.572, price: 139000, status: 'available' },
  { id: 'hawks-landing-l9b9',  communitySlug: 'hawks-landing', lotNumber: 'Lot 9, Block 9',  parcelNumber: 'RPB3225009009O', address: '3340 Granger St',                      acres: 0.609, price: 169000, status: 'available' },
  { id: 'hawks-landing-l10b9', communitySlug: 'hawks-landing', lotNumber: 'Lot 10, Block 9', parcelNumber: 'RPB3225009010O', address: '3304 Granger St',                      acres: 0.613, price: 169000, status: 'available' },

  // Block 10
  { id: 'hawks-landing-l1b10',  communitySlug: 'hawks-landing', lotNumber: 'Lot 1, Block 10',  parcelNumber: 'RPB3225010001O', address: '3097 Granger St / 6624 Crown Crescent', acres: 0.680, price: 139000, status: 'available' },
  { id: 'hawks-landing-l2b10',  communitySlug: 'hawks-landing', lotNumber: 'Lot 2, Block 10',  parcelNumber: 'RPB3225010002O', address: '3066 Lancer Ave / 6640 Crown Crescent',  acres: 0.819, price: 144000, status: 'available' },
  { id: 'hawks-landing-l8b10',  communitySlug: 'hawks-landing', lotNumber: 'Lot 8, Block 10',  parcelNumber: 'RPB3225010008O', address: '3303 Granger St',                        acres: 0.533, price: 139000, status: 'available' },
  { id: 'hawks-landing-l9b10',  communitySlug: 'hawks-landing', lotNumber: 'Lot 9, Block 10',  parcelNumber: 'RPB3225010009O', address: '3333 Granger St',                        acres: 0.541, price: 139000, status: 'available' },
  { id: 'hawks-landing-l10b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 10, Block 10', parcelNumber: 'RPB3225010010O', address: '3363 Granger St',                        acres: 0.550, price: 134000, status: 'available' },
  { id: 'hawks-landing-l11b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 11, Block 10', parcelNumber: 'RPB3225010011O', address: '3395 Granger St',                        acres: 0.538, price: 134000, status: 'available' },
  { id: 'hawks-landing-l12b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 12, Block 10', parcelNumber: 'RPB3225010012O', address: '3429 Granger St',                        acres: 0.503, price: 134000, status: 'available' },
  { id: 'hawks-landing-l13b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 13, Block 10', parcelNumber: 'RPB3225010013O', address: '3461 Granger St',                        acres: 0.528, price: 134000, status: 'available' },
  { id: 'hawks-landing-l14b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 14, Block 10', parcelNumber: 'RPB3225010014O', address: '3493 Granger St',                        acres: 0.550, price: 134000, status: 'available' },
  { id: 'hawks-landing-l20b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 20, Block 10', parcelNumber: 'RPB3225010020O', address: '3384 Lancer Ave',                        acres: 0.550, price: 174000, status: 'available' },
  { id: 'hawks-landing-l21b10', communitySlug: 'hawks-landing', lotNumber: 'Lot 21, Block 10', parcelNumber: 'RPB3225010021O', address: '3344 Lancer Ave',                        acres: 0.505, price: 174000, status: 'available' },

  // Block 11
  { id: 'hawks-landing-l6b11',  communitySlug: 'hawks-landing', lotNumber: 'Lot 6, Block 11',  parcelNumber: 'RPB3225011006O', address: '3185 Lancer Ave', acres: 0.684, price: 149000, status: 'available' },
  { id: 'hawks-landing-l7b11',  communitySlug: 'hawks-landing', lotNumber: 'Lot 7, Block 11',  parcelNumber: 'RPB3225011007O', address: '3235 Lancer Ave', acres: 0.717, price: 149000, status: 'available' },
  { id: 'hawks-landing-l8b11',  communitySlug: 'hawks-landing', lotNumber: 'Lot 8, Block 11',  parcelNumber: 'RPB3225011008O', address: '3287 Lancer Ave', acres: 0.750, price: 159000, status: 'available' },
  { id: 'hawks-landing-l9b11',  communitySlug: 'hawks-landing', lotNumber: 'Lot 9, Block 11',  parcelNumber: 'RPB3225011009O', address: '3337 Lancer Ave', acres: 0.807, price: 159000, status: 'available' },
  { id: 'hawks-landing-l10b11', communitySlug: 'hawks-landing', lotNumber: 'Lot 10, Block 11', parcelNumber: 'RPB3225011010O', address: '3377 Lancer Ave', acres: 0.808, price: 159000, status: 'available' },
  { id: 'hawks-landing-l11b11', communitySlug: 'hawks-landing', lotNumber: 'Lot 11, Block 11', parcelNumber: 'RPB3225011011O', address: '3407 Lancer Ave', acres: 0.916, price: 159000, status: 'available' },
  { id: 'hawks-landing-l12b11', communitySlug: 'hawks-landing', lotNumber: 'Lot 12, Block 11', parcelNumber: 'RPB3225011012O', address: '3439 Lancer Ave', acres: 0.969, price: 159000, status: 'available' },
];

// Lots are sourced from the master Google Sheet (1ES3Jjgz…) via the Apps
// Script API and synced at build time by scripts/sync-lots-from-master-sheet.mjs.
// `manualLots` is kept around as a legacy/fallback layer but is no longer
// the primary source — edit the SHEET to change website lot data.
export const lots: Lot[] = generatedMasterLots;

// Status visibility on the public /available-lots/ pages.
// - 'spec-in-progress' lots live on /quick-move-ins/, NOT on /available-lots/
// - 'sold' lots are removed entirely (no need to surface dead inventory)
// - 'available', 'reserved', 'under-contract' all show with appropriate badges
//   (reserved + under-contract are kept visible as activity signals)
const HIDE_FROM_AVAILABLE_LOTS: Set<LotStatus> = new Set(['spec-in-progress', 'sold']);

// Helper: lots in a community, filtered to only those buyers should see on
// /available-lots/, in display order — available first, then reserved,
// under-contract.
export function lotsByCommunity(slug: string): Lot[] {
  const statusOrder: Record<LotStatus, number> = {
    'available':         0,
    'spec-in-progress':  1,
    'reserved':          2,
    'under-contract':    3,
    'sold':              4,
  };
  return lots
    .filter(l => l.communitySlug === slug && !HIDE_FROM_AVAILABLE_LOTS.has(l.status))
    .sort((a, b) =>
      statusOrder[a.status] - statusOrder[b.status]
      || a.lotNumber.localeCompare(b.lotNumber, undefined, { numeric: true })
    );
}

// All lots (unfiltered) — for internal/admin contexts that need to see
// everything regardless of status.
export function allLotsByCommunity(slug: string): Lot[] {
  return lots.filter(l => l.communitySlug === slug);
}

// Helper: count lots per community by status (used in /available-lots/ stats bar)
export function lotCountByStatus(slug: string) {
  const counts: Record<LotStatus, number> = {
    available: 0, 'spec-in-progress': 0, reserved: 0, 'under-contract': 0, sold: 0,
  };
  for (const l of lots) {
    if (l.communitySlug === slug) counts[l.status]++;
  }
  return counts;
}
