// Spec home inventory — source of truth for /quick-move-ins/.
//
// A "spec home" is a home Odyssey is building on a specific lot with a chosen
// floor plan but no buyer yet. Buyers can claim a spec at any stage of the
// build — earlier = more finish customization, later = move in sooner.
//
// The `specHomes` array below is AUTO-GENERATED by `scripts/sync-odyssey-jobs.mjs`
// from the Job Progress Google Sheet. Don't edit it by hand — edit the sheet
// and re-run the sync. See `.claude/skills/sync-odyssey-jobs/SKILL.md`.

import { generatedSpecs } from './_generatedSpecs';
import { lots } from './lots';

export type SpecHomeStatus = 'available' | 'reserved' | 'under-contract' | 'sold';

export interface SpecHome {
  id: string;                  // Stable id, e.g. 'granite-creek-5118-eagle-creek-rd'
  communitySlug: string;       // Matches Community.slug in communities.ts
  lotNumber: string;           // e.g., "Lot 11, Block 12"
  address: string;             // Required — spec homes always have an address
  planSlug: string;            // Slug from plans.ts — the floor plan being built
  tentativeCompletion: string; // Display string, e.g. "January 2027" or "Coming soon"
  status: SpecHomeStatus;
  price?: number;              // USD asking. Omit for "Coming Soon"
  notes?: string;              // Optional buyer-facing detail
}

// Spec homes are sourced from TWO places:
//   1. Job Progress sheet (via _generatedSpecs.ts) — has rich build detail
//      (plan, tentative completion, photos coming later)
//   2. Master Lot Inventory sheet (via lots.ts, status='spec-in-progress') —
//      has lot detail (address, acres, price) but may lack plan/completion
//      if the build isn't yet logged in Job Progress
//
// We merge both, preferring Job Progress entries (richer data) when a lot
// appears in both. Master-only entries show with placeholder plan/completion
// values that the UI handles gracefully.
function buildMergedSpecHomes(): SpecHome[] {
  // Index Job Progress specs by a composite key so we can detect duplicates
  const keyOf = (slug: string, lotNumber: string) =>
    `${slug}::${String(lotNumber).replace(/\s+/g, '').toLowerCase()}`;
  const jpKeys = new Set(generatedSpecs.map(s => keyOf(s.communitySlug, s.lotNumber)));

  // Convert master-sheet spec-in-progress lots into SpecHome-shaped entries
  // (only those NOT already in Job Progress)
  const masterShells: SpecHome[] = lots
    .filter(l => l.status === 'spec-in-progress')
    .filter(l => !jpKeys.has(keyOf(l.communitySlug, l.lotNumber)))
    .map(l => ({
      id: l.id,
      communitySlug: l.communitySlug,
      lotNumber: l.lotNumber,
      address: l.address || '',  // may be empty for lots without addresses
      planSlug: '',              // unknown — UI shows "plan TBD"
      tentativeCompletion: 'Coming soon',
      status: 'available' as SpecHomeStatus,
      price: l.price,
      notes: l.notes,
    }));

  return [...generatedSpecs, ...masterShells];
}

export const specHomes: SpecHome[] = buildMergedSpecHomes();

// Helper: get all specs for a community in sensible display order
// (available first, sorted by tentative completion date ascending — earliest first)
const MONTH_INDEX: Record<string, number> = {
  'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
  'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12,
  'Spring': 3, 'Summer': 6, 'Fall': 9, 'Winter': 12,
};
function completionSortKey(s: SpecHome): number {
  const m = s.tentativeCompletion.match(/^(\w+)\s+(\d{4})$/);
  if (!m) return Number.MAX_SAFE_INTEGER;
  const month = MONTH_INDEX[m[1]] || 12;
  const year = parseInt(m[2], 10);
  return year * 12 + month;
}

export function specHomesByCommunity(slug: string): SpecHome[] {
  const statusOrder: Record<SpecHomeStatus, number> = {
    'available':       0,
    'reserved':        1,
    'under-contract':  2,
    'sold':            3,
  };
  return specHomes
    .filter(s => s.communitySlug === slug)
    .sort((a, b) =>
      statusOrder[a.status] - statusOrder[b.status]
      || completionSortKey(a) - completionSortKey(b)
    );
}

export function specHomeCountByStatus(slug: string) {
  const counts: Record<SpecHomeStatus, number> = { available: 0, reserved: 0, 'under-contract': 0, sold: 0 };
  for (const s of specHomes) {
    if (s.communitySlug === slug) counts[s.status]++;
  }
  return counts;
}

export function totalAvailableSpecs(): number {
  return specHomes.filter(s => s.status === 'available').length;
}
